# Generated by Django 5.0.14 on 2025-10-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_date', models.CharField(max_length=100)),
                ('confirm_backup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ComportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_port', models.CharField(max_length=255)),
                ('baud_rate', models.CharField(max_length=255)),
                ('parity', models.CharField(max_length=255)),
                ('stop_bit', models.CharField(max_length=255)),
                ('data_bit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('primary_contact_person', models.CharField(max_length=255)),
                ('secondary_contact_person', models.CharField(max_length=255)),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(max_length=254)),
                ('primary_phone_no', models.CharField(max_length=15)),
                ('secondary_phone_no', models.CharField(max_length=15)),
                ('primary_dept', models.CharField(max_length=255)),
                ('secondary_dept', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Data_Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=50)),
                ('shift_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InterlinkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Time', models.DateTimeField()),
                ('PartModel', models.CharField(max_length=50)),
                ('CompSrNo', models.CharField(max_length=150)),
                ('CompResultStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_password', models.CharField(max_length=255)),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='master_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField()),
                ('a1', models.IntegerField()),
                ('b', models.FloatField()),
                ('b1', models.IntegerField()),
                ('e', models.CharField(max_length=10)),
                ('d', models.FloatField()),
                ('o1', models.FloatField()),
                ('part_model', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('mastering', models.CharField(max_length=10)),
                ('probe_number', models.IntegerField()),
                ('channel_fixed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MasterInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveIntegerField()),
                ('minute', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comp_sr_no', models.CharField(max_length=100)),
                ('part_model', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=10)),
                ('parameter_name', models.CharField(max_length=100)),
                ('lsl', models.FloatField()),
                ('usl', models.FloatField()),
                ('ltl', models.FloatField()),
                ('utl', models.FloatField()),
                ('nominal', models.FloatField()),
                ('output', models.FloatField()),
                ('max_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('tir_value', models.FloatField()),
                ('statusCell', models.CharField(max_length=100)),
                ('overall_status', models.CharField(max_length=100)),
                ('tapper', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operator_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_no', models.CharField(max_length=10)),
                ('operator_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=10)),
                ('part_model', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('char_lock', models.CharField(max_length=100)),
                ('char_lock_limit', models.CharField(max_length=100)),
                ('tapper', models.CharField(max_length=100)),
                ('punch_no', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='part_retrived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TableClearFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clear_table', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_model', models.CharField(max_length=255)),
                ('parameter_name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=10)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('part_model', 'parameter_name')},
            },
        ),
        migrations.CreateModel(
            name='paraTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=10)),
                ('parameter_name', models.CharField(blank=True, max_length=100)),
                ('fixed_channel', models.CharField(blank=True, max_length=10)),
                ('channel_no', models.CharField(blank=True, max_length=10)),
                ('single_double', models.BooleanField(default=False)),
                ('low_master', models.CharField(blank=True, max_length=100)),
                ('high_master', models.CharField(blank=True, max_length=100)),
                ('nominal', models.CharField(blank=True, max_length=100)),
                ('lsl', models.CharField(blank=True, max_length=100)),
                ('usl', models.CharField(blank=True, max_length=100)),
                ('ltl', models.CharField(blank=True, max_length=100)),
                ('utl', models.CharField(blank=True, max_length=100)),
                ('master_grp', models.CharField(blank=True, max_length=10)),
                ('step_no', models.CharField(blank=True, max_length=10)),
                ('auto_man', models.BooleanField(default=False)),
                ('timer', models.CharField(blank=True, max_length=100)),
                ('digits', models.CharField(blank=True, max_length=10)),
                ('id_od', models.CharField(blank=True, max_length=10)),
                ('parameter_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_data', to='app.parameter_settings')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftRedirectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('redirected', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('shift_name', 'date')},
            },
        ),
    ]
